all: comm_progs

comm_progs:
	g++ -o news.o news.cpp -lcurl

# docker run -it --rm -v "D:\System\Documents\GitHub\Personal\TEC\Semestre 2\Estructuras de datos\Caso #1:/home" gcc bash
# apt update -y
# apt install curl
sd